### ISSUE TITLE
VM discovery ? 

### ISSUE THREAD

**Issue by omueller** [takala-jp/zabbix-proxmox#13]
Hello and thanks for this very interesting and promising project!  Not really an issue but a small question:  I have a few proxmox nodes (stand-alone, not in a cluster), and I'm looking for a template with automatic discovery of all the VMs running:  your project seems to be the closest match.   Maybe you already tried something like this ?   Otherwise I will try sometime later.   Goal would be to have vm name, kvm id, status (on/off), cpu load, ram usage, network usage, disk io, agent information (ip), etc. for each VM. 

Do you think it would be possible ?  If you have any suggestion, please feel free to tell, thanks in advance ! (I only have basic Zabbix knowledge, just configuration, no template coding yet.)

Best regards, Olivier

**Comment by takala-jp** [comment]
Hi Olivier, thank you for your interest. This project is focused on the cluster details although it also works for single hosts. Individual guest metrics are not on the roadmap. I believe that is much better handled by a zabbix agent on the guest.
