### ISSUE TITLE
I can't get data

### ISSUE THREAD

**Issue by BayramGrbz45** [takala-jp/zabbix-proxmox#17]
`root@pve1:/etc/zabbix# ./proxmox_cluster.py -a 192.168.0.201 -u zabbix@pve -p 15901590 -t mon.testlab.com -d
`
Error while sending discovery data: Command '['/usr/bin/zabbix_sender', '-c/etc/zabbix/zabbix_agentd.conf', '-smon.testlab.com', '-kproxmox.nodes.discovery', '-o{"data": [{"{#NODE}": "pve1"}, {"{#NODE}": "pve2"}]}']' returned non-zero exit status 2.

`root@pve1:/etc/zabbix# zabbix_sender -v -c /etc/zabbix/zabbix_agentd.conf -s pve1.testlab.com -k promox.cluster.quorate -o 1`
Response from "192.168.0.164:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000057"
sent: 1; skipped: 0; total: 1

**Comment by tuxick** [comment]
Same problem here, zabbix_sender and server 4.4

**Comment by takala-jp** [comment]
The -t parameter should reference the proxmox host in zabbix (to which you attached the template), not the zabbix host itself. 

Try running it as:

`./proxmox_cluster.py -a 192.168.0.201 -u zabbix@pve -p 15901590 -t pve1.testlab.com -d`

EDIT: Sorry, the zabbix_sender fails as well. You want to get processed 1, failed 0. 

Is pve1.testlab.com configured in zabbix with the template from this repo?

**Comment by takala-jp** [comment]
Closing as stale
