### ISSUE TITLE
error while sending values

### ISSUE THREAD

**Issue by chrisgassen** [takala-jp/zabbix-proxmox#2]
Hey there,
first of all: thank you for this template!

I am however running in a slight problem.

For testing purposes I tried manually running the script as follows:
`/root/sys/proxmox_cluster.py -v -a adelie.domain.tld -u zabbix@pve -p zabbix -t CLUSTER.domain.tld`

The last lines of the output are the following:
```
CLUSTER.domain.tld proxmox.node.vram_used.[emperor] 1582624195 3453960192
CLUSTER.domain.tld proxmox.node.vcpu_allocated.[emperor] 1582624195 15

('Error while sending values:', 'str() takes at most 1 argument (2 given)')
```

I believe that there is a problem in proxmox_cluster.py script somewehere in the block between 302 and 313.

Any help would be greatly appreciated!
Thanks in advance.

**Comment by chrisgassen** [comment]
Ok, my python skills are apparently not as bad as I thought (after some reading though)...

In the 2nd "try" in the block of "#send item values" there is a line (328) looking like this:
`result = zabbix_sender.communicate(bytes(item_data, 'UTF-8'))`
Change it to this:
`result = zabbix_sender.communicate(bytes(item_data).encode('UTF-8'))`

I understand that you would actually want to encode the data and not pass the enocing through as a value or something. Works for me ;)

**Comment by takala-jp** [comment]
Thank you for that, I'll check it out.

Which version of python are you testing this against? Someone else reported a similar issue with python2. In that case can you try running it against python3.

**Comment by chrisgassen** [comment]
Yes I am running python2.7

I just tried it with python3. Then it has the following problem (as you expected):
`Error while sending values: string argument without an encoding`

I guess a good option would be to change the shebang in the script to: `#!/usr/bin/python3`
Then your line works as expected.

**Comment by takala-jp** [comment]
That sounds like a good idea. I'll update the shebang to be more explicit and close this issue.
