### ISSUE TITLE
Proxmox 5x works fine but not 6.3

### ISSUE THREAD

**Issue by martiinezz** [takala-jp/zabbix-proxmox#20]
Hi, so I have such issue on 6.3 that discovery works fine - but not the main script :(

Traceback (most recent call last):
  File "/usr/local/bin/proxmox_cluster.py", line 192, in <module>
    node_status = proxmox.nodes(n).status.get()
  File "/usr/local/lib/python3.6/site-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.6/site-packages/proxmoxer/core.py", line 94, in _request
    resp.reason, resp.content))
proxmoxer.core.ResourceException: 595 Errors during connection establishment, proxy handshake: Connection refused - b''

Any ideas why discovery works fine (I get list of nodes no problem) but main script fails?

The same setup with Proxmox 5 works like a charm.

**Comment by takala-jp** [comment]
Does the cluster have quorum? You can check in the GUI: Datacentre => HA

Without quorum it could be possible for a node to be aware of the number of nodes but not the VMs which could explain why only discovery works. Really not sure about this though.

FWIW, the script has been successfully tested against a healthy Proxmox 6 cluster.

I'd be interested in hearing the solution to this issue.

**Comment by martiinezz** [comment]
This is fresh clean cluster

![image](https://user-images.githubusercontent.com/19732099/109794014-b0f5fa80-7c15-11eb-910c-6a6d97c89d10.png)

**Comment by martiinezz** [comment]
Weird thing I've tried script today and it works. Both discovery and VMs details.

**Comment by takala-jp** [comment]
Bizarre, if you ever happen to find out how this occurs I'd be interested in knowing.

Thank you for the update!
