### ISSUE TITLE
CPU, Ram, disk usage, net in and out for VM and CT needed

### ISSUE THREAD

**Issue by webafrancois** [takala-jp/zabbix-proxmox#21]
I have a lot of CTs and VMs and I need to monitor the CPU, RAM, disk space used and network in and out.
How can I use the API to get the information of each one?
Is it possible to have a discovery rule to see these hosts appear or how to declare them in Zabbix?

I can see it in the json of the API : 
https://proxmox.mynode.com:8006/api2/json/nodes/mynode/lxc
- name
- mem / maxmem
- netin
- netout
- swap / maxswap
- status
and other data you should be relevant.
https://proxmox.mynode.com:8006/api2/json/nodes/mynode/qemu

**Comment by takala-jp** [comment]
Yes, other than disk space used I believe you can get that information out of the API. It is not included in this scripts as it focuses on resources of the cluster and its nodes. 

Monitoring guests is better handled by the zabbix agent.

**Comment by webafrancois** [comment]
Yes, I know that Zabbix Agent can extract these data, but I wouldn't install zabbix agent in each CT or VM only to inspect these data.
Of course, your script focuses to the cluster and its nodes. 
But how can I inspect data I see in the web interface of proxmox without Zabbix agent installed in each CT/VM ?

**Comment by takala-jp** [comment]
Closing issue as out of scope. Zabbix has great facilities to automate host monitoring using the agent which seems to be a better fit for this purpose.
