### ISSUE TITLE
flag to set the zabbix host missing

### ISSUE THREAD

**Issue by fansari** [takala-jp/zabbix-proxmox#24]
I tried to get this running inside a zabbix-proxy container.

For running in a container (zabbix host or zabbix proxy) you would have to pass the "-z" parameter to zabbix_sender to configure the Zabbix host.

Also there is no Zabbix agent running in such a container so the config file makes not really sense there.

I have put a Zabbix config file into my zabbix-proxy container and adapted the proxmox_cluster.py at all necessary places and added my zabbix proxy internal docker container IP here.

Perhaps a flag to pass the Zabbix host would be great (-z is already used for the zabbix_sender binary).

**Comment by takala-jp** [comment]
Hey, the working theory is that zabbix_sender will use the zabbix_agent configuration file in which you  configure the the zabbix host. You do not need the agent, but do need the config and specify the location with -c if not in the default spot.

Does that not work for you?

**Comment by fansari** [comment]
You are right. If I set "ServerActive" to the IP of the zabbix-proxy in the container it works.

It was not obvious to me to put a configuration file in a container when the service is not running there.
