### ISSUE TITLE
proxmoxer.core.ResourceException: 401 Unauthorized: permission denied - invalid PVE ticket - b''

### ISSUE THREAD

**Issue by abhisingh1142** [takala-jp/zabbix-proxmox#25]
Hey,
After executing the below command we are getting a "401 Unauthorized: permission denied" error.

/usr/lib/zabbix/bin/proxmox_cluster.py -a [pmx01.your.tld] -u zabbix@pve -p [password] -t [proxmox.tokyo.prod]

Error:
Traceback (most recent call last):
  File "/usr/lib/zabbix/bin/proxmox_cluster.py", line 192, in <module>
    node_status = proxmox.nodes(n).status.get()
  File "/usr/local/lib/python3.7/dist-packages/proxmoxer/core.py", line 123, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.7/dist-packages/proxmoxer/core.py", line 110, in _request
    (self._store["serializer"].loads(resp) or {}).get('errors')
proxmoxer.core.ResourceException: 401 Unauthorized: permission denied - invalid PVE ticket - b''

**Comment by takala-jp** [comment]
Hi there,

I believe the important part of that error is: `401 Unauthorized: permission denied - invalid PVE ticket` which looks like the username/password are not configured correctly.

(handling the exception a bit nicer will go on the todo list)

**Comment by abhisingh1142** [comment]
Hey,
Thanks for your response. the issue got resolved. The username & password was right, it was related to NTP synchronization between the nodes.
