### ISSUE TITLE
ModuleNotFoundError: No module named 'proxmoxer'

### ISSUE THREAD

**Issue by boboinmo2021** [takala-jp/zabbix-proxmox#27]
I am running on ubuntu 18.04. I walked through the whole process and all seemed well but when I try to run the script I get the following: 

rminor@u2000:~/scripts$ pip install proxmoxer
Collecting proxmoxer
Installing collected packages: proxmoxer
Successfully installed proxmoxer-1.2.0

Its installed

rminor@u2000:~/scripts$ ./proxmox_cluster.py -a 10.102.1.2 -u zabbix@pve -p mypass -t ProxmoxCluster -d
Traceback (most recent call last):
  File "./proxmox_cluster.py", line 29, in <module>
    from proxmoxer import ProxmoxAPI
ModuleNotFoundError: No module named 'proxmoxer'

Tried running as sudo and still no dice!

**Comment by takala-jp** [comment]
Can you try running `pip3 install proxmoxer`

**Comment by boboinmo2021** [comment]
OK that appears to have done the trick for proxmoxer. It seems I am getting information from the cluster, but now with another error. 

Error while sending discovery data: Command '['/usr/bin/zabbix_sender', '-c/etc/zabbix/zabbix_agentd.conf', '-sProxmoxCluster', '-kproxmox.nodes.discovery', '-o{"data": [{"{#NODE}": "proxmox4"}, {"{#NODE}": "proxmox8"}, {"{#NODE}": "proxmox7"}, {"{#NODE}": "proxmox10"}, {"{#NODE}": "proxmox9"}, {"{#NODE}": "proxmox1"}, {"{#NODE}": "proxmox12"}, {"{#NODE}": "proxmox5"}, {"{#NODE}": "proxmox13"}, {"{#NODE}": "proxmox3"}, {"{#NODE}": "proxmox2"}, {"{#NODE}": "proxmox6"}]}']' returned non-zero exit status 2. If you'd like I can open this in another query, and mark this as closed. Might be the zabbix_sender?

**Comment by boboinmo2021** [comment]
to clarify this is an old cluster running proxmox v5.4. We will also be monitoring the new cluster a proxmox v7

**Comment by boboinmo2021** [comment]
Any answer for this, just a hint. I get its newb stuff and I know I am not a zabbix pro

**Comment by takala-jp** [comment]
Zabbix returns with exit status 2 which implies that at least one of the values failed (https://www.zabbix.com/documentation/current/en/manpages/zabbix_sender).

`If data was sent, but processing of at least one of the values failed, the exit status is 2`

This issue has been reported by two other people as well. It is unclear exactly why zabbix does not return 0 as all values appear to be processed. 

The hosts do appear in zabbix despite the error correct?

**Comment by derekschartung** [comment]
Same issue here:
`root@zabbix:/home/ubuntu/zabbix-proxmox# python3 /usr/lib/zabbix/bin/proxmox_cluster.py -c /etc/zabbix/zabbix_agentd.conf  -a 172.16.0.25 -u zabbix@pve -p PASS -t 172.16.0.40 -o  -d
Response from "127.0.0.1:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000088"
sent: 1; skipped: 0; total: 1
Error while sending discovery data: Command '['/usr/bin/zabbix_sender', '-c/etc/zabbix/zabbix_agentd.conf', '-s172.16.0.40', '-kproxmox.nodes.discovery', '-o{"data": [{"{#NODE}": "pve"}]}']' returned non-zero exit status 2.`

**Comment by takala-jp** [comment]
Script was updated to handle this scenario more gracefully. Please refer to the updated documentation. Closing issue accordingly.
