### ISSUE TITLE
Incorrect command output 

### ISSUE THREAD

**Issue by lode00** [takala-jp/zabbix-proxmox#29]
Good afternoon! Thank you more for the code. However, there are some issues with the value output. 
The first problem is that there is no information about ram, cpu by cluster.
`[root@hektor sbin]# /usr/bin/python3 /usr/local/sbin/proxmox_cluster.py -vv -a 192.168.0.5 -u zabbix@pve -p xxxxx -t hektor
{
    }, "status": {
        "quorate": 1,
        "cpu_total": 0,
        "cpu_usage": 0.0,
        "ram_total": 0,
        "ram_used": 0,
        "ram_free": 0,
        "ram_usage": 0,
        "ksm_sharing": 6547615744,
        "vcpu_allocated": 0,
        "vram_allocated": 0,
        "vhdd_allocated": 0,
        "vram_used": 0,
        "vram_usage": 0,
        "vms_running": 0,
        "vms_stopped": 0,
        "vms_total": 0,
        "lxc_running": 0,
        "lxc_stopped": 0,
        "lxc_total": 0,
        "vm_templates": 0,
        "nodes_total": 1,
        "nodes_online": 1
    },
    }, "nodes": {
        }, "hector": {
            "online": 1,
            "vms_total": 0,
            "vms_running": 0,
            "lxc_total": 0,
            "lxc_running": 0,
            "vcpu_allocated": 0,
            "vram_allocated": 0,
            "vhdd_allocated": 0,
            "vram_used": 0,
            "ksm_sharing": 6547615744,
            "cpu_total": 0,
            "cpu_usage": 0,
            "ram_total": 0,
            "ram_used": 0,
            "ram_free": 0,
            "ram_usage": 0.0
        }
    }
}`
`hector promox.cluster.quorate 1638268539 1
hector promox.cluster.cpu_total 1638268539 0
hector promox.cluster.cpu_usage 1638268539 0.0
hectare promox.cluster.ram_total 1638268539 0
hectare promox.cluster.ram_used 1638268539 0
hectare promox.cluster.ram_free 1638268539 0
hectare promox.cluster.ram_usage 1638268539 0
hectare promox.cluster.ksm_sharing 1638268539 6547615744
hectares promox.cluster.vcpu_allocated 1638268539 0
hectare promox.cluster.vram_allocated 1638268539 0
hectare promox.cluster.vhdd_allocated 1638268539 0
hectare promox.cluster.vram_used 1638268539 0
hectares promox.cluster.vram_usage 1638268539 0
hectare promox.cluster.vms_running 1638268539 0
hectare promox.cluster.vms_stopped 1638268539 0
hectares promox.cluster.vms_total 1638268539 0
hectare promox.cluster.lxc_running 1638268539 0
hectare promox.cluster.lxc_stopped 1638268539 0
hectare promox.cluster.lxc_total 1638268539 0
hector promox.cluster.vm_templates 1638268539 0
hectare promox.cluster.nodes_total 1638268539 1
hectare promox.cluster.nodes_online 1638268539 1
hectare proxmox.node.online.[hectare] 1638268539 1
hectare proxmox.node.vms_total.[hectare] 1638268539 0
hectare proxmox.node.vms_running.[hectare] 1638268539 0
hectare proxmox.node.lxc_total.[hectare] 1638268539 0
hectare proxmox.node.lxc_running.[hectare] 1638268539 0
hectare proxmox.node.vcpu_allocated.[hectare] 1638268539 0
hector proxmox.node.vram_allocated.[hector] 1638268539 0
hectare proxmox.node.vhdd_allocated.[hectare] 1638268539 0
hectare proxmox.node.vram_used.[hectare] 1638268539 0
hectare proxmox.node.ksm_sharing.[hectare] 1638268539 6547615744
hectare proxmox.node.cpu_total.[hectare] 1638268539 0
hectare proxmox.node.cpu_usage.[hectare] 1638268539 0
hectare proxmox.node.ram_total.[hectare] 1638268539 0Well, the problem writes every 10 minutes, because most likely the wrong cron is configured 
hectare proxmox.node.ram_used.[hectare] 1638268539 0
hectare proxmox.node.ram_free.[hectare] 1638268539 0
hector proxmox.node.ram_usage.[hector] 1638268539 0.0
`
(b'Response from "zabbix.ru:10051": 'processed: 38; failed: 0; total: 38; seconds spent: 0.000270"\nsent: 38; skipped: 0; total: 38\n', None)

-t is the name in zabbix, -a is the ip where proxmox is running.
![image](https://user-images.githubusercontent.com/62034233/144032894-323db537-3472-40fb-9260-d56118952bbf.png)
Well, the problem writes every 10 minutes, because most likely the wrong cron is configured 

Could you help what this could be related to?

**Comment by takala-jp** [comment]
Hi lode00, it looks like you are running a single Proxmox server, not a cluster:

` "nodes_total": 1`

With a single Proxmox server not all the cluster values exist.

**Comment by lode00** [comment]
Thanks, @takala-jp ! Yes, I am using 1 Proxmox server. I was hoping we could collect more metrics for the server.

**Comment by takala-jp** [comment]
The script is mainly intended to monitor a Proxmox cluster. Using it with a single server will work but cluster metrics are not available.
