### ISSUE TITLE
Unable to get data

### ISSUE THREAD

**Issue by matt2210** [takala-jp/zabbix-proxmox#31]
Hello i have an issue with the script : 

python3.9 /usr/lib/zabbix/bin/proxmox_cluster.py -a IPOFPROXMOX -u zabbix@pve -p PASSWORDMAGIC -t IPOFZABBIX -i -o -d

Response from "IPOFZABBIX:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000030"

sent: 1; skipped: 0; total: 1

python3.9 /usr/lib/zabbix/bin/proxmox_cluster.py -a  IPOFPROXMOX  -u zabbix@pve -p PASSWORDMAGIC -t IPOFZABBIX -i -o   

Response from "IPOFZABBIX:10051": "processed: 0; failed: 54; total: 54; seconds spent: 0.000754"

sent: 54; skipped: 0; total: 54

![image](https://user-images.githubusercontent.com/25546600/147700803-423cbda4-1916-4dc1-a9d4-1589afc980c6.png)

Anybody have an idea how to solve that ? 

Thanks

**Comment by takala-jp** [comment]
The `-t` should be the value of the Host you created in Zabbix, not the Zabbix server name or IP address of Zabbix. Based on the screenshot I would suggest to use the value `Proxmox`.

**Comment by matt2210** [comment]
Is working thx

**Comment by takala-jp** [comment]
Great, happy to hear that.
