### ISSUE TITLE
Trying discovery storage getting error

### ISSUE THREAD

**Issue by funyfizik** [takala-jp/zabbix-proxmox#36]
Trying discovery storage getting error in WEB 6.0: Cannot send request: wrong discovery rule type. [host_discovery.php:794 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CTask->create() → CTask->validateCreate() → CTask->checkEditableItems() → CApiService::exception() in include/classes/api/services/CTask.php:444]

**Comment by takala-jp** [comment]
Sorry, I don't understand what you are trying to do. Please provide more details on how to reproduce this error message.

**Comment by funyfizik** [comment]
sory my mistake
