### ISSUE TITLE
Unable to open zabbix_sender

### ISSUE THREAD

**Issue by RadianceNL** [takala-jp/zabbix-proxmox#4]
I'm getting the following error when executing this command using Zabbix on a Raspberry Pi.
I've installed zabbix-sender through apt-get install and running Python 3.
Any advise where to look at? Thanks in advance!

Command:
`
/etc/proxmox_cluster.py -a 192.168.178.2 -u zabbix@pve -p password -t proxmox.proxmox.prod -d
`
Error:
`
Unable to open zabbix_sender: Command '['/usr/bin/zabbix_sender', '-c/etc/zabbix/zabbix_agentd.conf', '-sproxmox.proxmox.prod', '-kproxmox.nodes.discovery', '-o{"data": [{"{#NODE}": "pve"}]}']' returned non-zero exit status 2.
`

**Comment by takala-jp** [comment]
I'm guessing that zabbix_sender is not in /usr/bin. Find out where zabbix_sender is actually installed, and what it is called, and call the script with the -z parameter:

  `-z /full/path/to/zabbix_sender`

**Comment by RadianceNL** [comment]
zabbix_sender is in /usr/bin and when adding the -z option with the full path I get the same error.
I copied the above command with 'password' as password which isn't the password and I got an error back that it couldn't authenticate to the Proxmox API. Does this mean that zabbix_sender does actually work or is it just the script returning that it couldn't connect?

When I add http in front of the IP address I get this error btw:
`
Promox API call failed: HTTPSConnectionPool(host='http', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75f22a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
`

**Comment by takala-jp** [comment]
That's right. You can only specify the hostname/ip and optionally a port if the API is not listening on the default. Presumably the API call was already working as otherwise you would not have seen the zabbix error as there was no data to send.

Is the zabbix configuration file in the default (/etc/zabbix/zabbix_agentd.conf) location?

And, if so, is it configured correctly? 

The configuration file is an argument when calling zabbix_sender.

EDIT:

Test if zabbix_sender is functional:

```
tc@pi:~$ /usr/bin/zabbix_sender -v -c /etc/zabbix/zabbix_agentd.conf -s proxmox.tokyo.prod -k promox.cluster.quorate -o 1 
info from server: "processed: 1; failed: 0; total: 1; seconds spent: 0.000036"
sent: 1; skipped: 0; total: 1

```

The -s parameter should of course be followed by the host name you configured for Proxmox in the zabbix front end.

**Comment by jstride** [comment]
I'm having this issue too - zabbix_sender works but it's the auth against the Proxmox JSON API that is failing. The password I am using works for the Proxmox GUI:

`Promox API call failed: Couldn't authenticate user: zabbix@pve to https://xxx.xxx:8006/api2/json/access/ticket`

**Comment by takala-jp** [comment]
@jstride that is a different issue, you are not getting to the zabbix_sender part yet. When logging in to the GUI with the zabbix credentials which realm do you select? If it is "Linux PAM standard" the user parameter should reflect that: 

`-u zabbix@pam` 

The documentation doesn't mention this and needs to be updated.

**Comment by jstride** [comment]
`./proxmox_cluster.py -a samwise.mgmt -u zabbix@pve -p XXXXX -t meriadoc.mgmt -d -v
{"data": [{"{#NODE}": "samwise"}]}
Unable to open zabbix_sender: Command '['/usr/bin/zabbix_sender', '-c/etc/zabbix/zabbix_agentd.conf', '-smeriadoc.mgmt', '-kproxmox.nodes.discovery', '-o{"data": [{"{#NODE}": "samwise"}]}']' returned non-zero exit status 2.`

I login with zabbix@pve and the password and it works fine via the Web UI.

`./proxmox_cluster.py -a samwise.mgmt -u zabbix@pam -p XXXX -t meriadoc.mgmt -d -v
Promox API call failed: Couldn't authenticate user: zabbix@pam to https://samwise.mgmt:8006/api2/json/access/ticket`

**Comment by takala-jp** [comment]
What happens when you run this:

`/usr/bin/zabbix_sender -v -c /etc/zabbix/zabbix_agentd.conf -s meriadoc.mgmt -k promox.cluster.quorate -o 1`

**Comment by jstride** [comment]
meriadoc is the Zabbix and samwise is Proxmox:

`root@meriadoc:~# /usr/bin/zabbix_sender -v -c /etc/zabbix/zabbix_agentd.conf -s meriadoc.mgmt -k promox.cluster.quorate -o 1
Response from "127.0.0.1:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000024"
sent: 1; skipped: 0; total: 1`

however

`/usr/bin/zabbix_sender -v -c /etc/zabbix/zabbix_agentd.conf -s samwise.mgmt -k promox.cluster.quorate -o 1
Response from "127.0.0.1:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000014"
sent: 1; skipped: 0; total: 1`

**Comment by takala-jp** [comment]
Both those commands failed (processed: 0; failed: 1). 

The name you use after the -s should be the hostname you defined for Proxmox in the Zabbix GUI  and to which you attached the template.

**Comment by jstride** [comment]
Thanks - that was the fix, was using the hostname of the server rather than the Zabbix name!

**Comment by takala-jp** [comment]
Great, happy to hear it is working.
